name       : praat
version    : 6.0.28
release    : 1
source     :
    - https://github.com/praat/praat/archive/v6.0.28.tar.gz : d53a9be75821e0c722b8caf89922b5bb210ae965800be5d09edf70ffd1c9d3bf
license    : GPL-2.0
summary    : A software package for the scientific analysis of speech in phonetics
description: |
    Praat is a free computer software package for the scientific analysis of speech in phonetics
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
setup      : |
    cp makefiles/makefile.defs.linux.pulse ./makefile.defs
build      : |
    %make
install    : |
    install -D -m 0755 praat $installdir/usr/bin/praat
