name       : praat
version    : 6.2.10
release    : 10
source     :
    - https://github.com/praat/praat/archive/refs/tags/v6.2.10.tar.gz : f6358b2c6a967afe89882720d503c74221b364c563e1e4316a2d73c9f0c22bcd
homepage   : http://www.praat.org/
license    : GPL-3.0-or-later
component  : office.scientific
summary    : A software package for the scientific analysis of speech in phonetics
description: |
    Praat is a speech analysis tool used for doing phonetics by computer. Praat can analyse, synthesize, and manipulate speech, and create high-quality pictures for your publications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
setup      : |
    cp makefiles/makefile.defs.linux.pulse ./makefile.defs
build      : |
    %make
install    : |
    install -Dm00755 praat $installdir/usr/bin/praat
    install -Dm00644 main/praat.desktop $installdir/usr/share/applications/praat.desktop
    install -Dm00644 main/praat.svg $installdir/usr/share/pixmaps/praat.svg
