name       : praat
version    : 6.0.36
release    : 5
source     :
    - https://github.com/praat/praat/archive/v6.0.36.tar.gz : 1829eedf0c03780ce29c2b1a778b4065ff19d3959dbe919b25e721206f113c52
license    : GPL-2.0
component  : office.scientific
summary    : A software package for the scientific analysis of speech in phonetics
description: |
    Praat is a free computer software package for the scientific analysis of speech in phonetics
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
setup      : |
    cp makefiles/makefile.defs.linux.pulse ./makefile.defs
build      : |
    %make
install    : |
    install -D -m 00755 praat $installdir/usr/bin/praat
    install -Dm 00644 $pkgfiles/praat.desktop $installdir/usr/share/applications/praat.desktop
